# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the oeps/ directory with Sphinx
sphinx:
   configuration: oeps/conf.py
   fail_on_warning: true

# Set the version of python needed to build these docs.
build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

python:
   install:
   - requirements: requirements/dev.txt
